----------- 레벨 2

-- 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(*) cnt
FROM ANIMAL_INS ai
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE;

-- 루시와 엘라 찾기
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE FROM ANIMAL_INS ai
WHERE NAME = 'Lucy' OR NAME = 'Ella'
OR NAME = 'Pickle' OR NAME = 'Rogan'
OR NAME = 'Sabrina' OR NAME = 'Mitty';

-- 최솟값 구하기
SELECT MIN(DATETIME) FROM ANIMAL_INS ai;

-- 동명 동물 수 찾기
SELECT NAME, COUNT(*) FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
HAVING COUNT(*) >= 2
ORDER BY NAME;

-- 이름에 el이 들어가는 동물 찾기
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
WHERE UPPER(NAME) LIKE '%EL%' AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME;

-- 동물 수 구하기
SELECT COUNT(*) FROM ANIMAL_INS;

-- 입양 시각 구하기 (1)


----------- 레벨 3

-- 없어진 기록 찾기
SELECT ao.ANIMAL_ID, ao.NAME FROM ANIMAL_OUTS ao     -- 부모 테이블
LEFT OUTER JOIN ANIMAL_INS ai
ON ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE ai.ANIMAL_ID IS NULL
ORDER BY ao.ANIMAL_ID;

-- 있었는데요 없었습니다
SELECT ai.ANIMAL_ID, ai.NAME FROM ANIMAL_INS ai, ANIMAL_OUTS ao
WHERE ai.ANIMAL_ID = ao.ANIMAL_ID
AND ai.DATETIME > ao.DATETIME
ORDER BY ai.DATETIME;

-- 오랜 기간 보호한 동물 (1)
SELECT ai.NAME, ai.DATETIME FROM ANIMAL_INS ai
LEFT OUTER JOIN ANIMAL_OUTS ao
ON ao.ANIMAL_ID = ai.ANIMAL_ID
WHERE ao.ANIMAL_ID IS NULL
ORDER BY 2
FETCH FIRST 3 ROWS ONLY;